# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-28 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import kernel.action
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(default=uuid.uuid4, editable=False, max_length=120, verbose_name='Внешний ключ')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('from_email', models.TextField(verbose_name='from email')),
                ('recipients', models.TextField(verbose_name='recipients')),
                ('subject', models.TextField(verbose_name='subject')),
                ('body', models.TextField(verbose_name='body')),
                ('ok', models.BooleanField(db_index=True, default=False, verbose_name='ok')),
                ('date_sent', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date sent')),
            ],
            options={
                'verbose_name_plural': 'emails',
                'verbose_name': 'email',
                'ordering': ('-date_sent',),
            },
            bases=(kernel.action.ActionKernelModel, models.Model),
        ),
    ]
